version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: job_matcher
      POSTGRES_USER: job_matcher_user
      POSTGRES_PASSWORD: local_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    environment:
      - DATABASE_URL=postgresql://job_matcher_user:local_dev_password@postgres:5432/job_matcher
      - DEBUG=true
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/tmp/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: