apiVersion: v1
kind: ServiceMonitor
metadata:
  name: job-matcher-backend-monitor
  namespace: job-matcher
  labels:
    app: job-matcher-backend
spec:
  selector:
    matchLabels:
      app: job-matcher-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: job-matcher-frontend-monitor
  namespace: job-matcher
  labels:
    app: job-matcher-frontend
spec:
  selector:
    matchLabels:
      app: job-matcher-frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: job-matcher-alerts
  namespace: job-matcher
  labels:
    app: job-matcher
spec:
  groups:
  - name: job-matcher.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 10% for 5 minutes"
    
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency detected"
        description: "95th percentile latency is above 500ms"
    
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently"
    
    - alert: DatabaseConnectionFailed
      expr: up{job="postgres-exporter"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failed"
        description: "Cannot connect to PostgreSQL database"