apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: job-matcher-secrets
  namespace: job-matcher
spec:
  provider: gcp
  parameters:
    usePodServiceAccount: "true"
    secrets: |
      - resourceName: "projects/PROJECT_ID/secrets/job-matcher-db-password/versions/latest"
        path: "db-password"
      - resourceName: "projects/PROJECT_ID/secrets/job-matcher-firebase-config/versions/latest"
        path: "firebase-config"
      - resourceName: "projects/PROJECT_ID/secrets/job-matcher-jwt-secret/versions/latest"
        path: "jwt-secret"
      - resourceName: "projects/PROJECT_ID/secrets/job-matcher-vertex-ai-key/versions/latest"
        path: "vertex-ai-key"
      - resourceName: "projects/PROJECT_ID/secrets/job-matcher-ats-api-keys/versions/latest"
        path: "ats-api-keys"
  secretObjects:
  - secretName: job-matcher-secrets
    type: Opaque
    data:
    - objectName: db-password
      key: DB_PASSWORD
    - objectName: firebase-config
      key: FIREBASE_CONFIG
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: vertex-ai-key
      key: VERTEX_AI_KEY
    - objectName: ats-api-keys
      key: ATS_API_KEYS
